### ISSUE TITLE
Hi from TipRanks

### ISSUE THREAD

**Issue by benjamingr** [gpresland/tipranks#1]
Hi,

Benji from TipRanks here.

I would recommend against what you're doing here since we actually have systems in place to start pushing garbage and partial data in when you access the APIs this way. This is in addition to Imperva and Distil which will eat this scraper for breakfast. Your data will be inconsistent with what we have on the site and generally incorrect.

If you're interested, we actually do have an official documented API with the data - if you reach out to be (at benji@tipranks) we can gladly discuss giving you proper access to it.

Thanks for the interest in our data!

Benji

**Comment by gpresland** [comment]
Thanks Benji.

I added a note to the README should anyone else come across this project.
